export const GET_COMPNIES_REQUEST = "GET_COMPNIES_REQUEST";
export const GET_COMPNIES_SUCCESS = "GET_COMPNIES_SUCCESS";
export const GET_COMPNIES_FAILURE = "GET_COMPNIES_FAILURE";

export const POST_COMPNIES_REQUEST = "POST_COMPNIES_REQUEST";
export const POST_COMPNIES_SUCCESS = "POST_COMPNIES_SUCCESS";
export const POST_COMPNIES_FAILURE = "POST_COMPNIES_FAILURE";
