export const GET_COMPNIES_REQUEST = "GET_COMPNIES_REQUEST";
export const GET_COMPNIES_SUCCESS = "GET_COMPNIES_SUCCESS";
export const GET_COMPNIES_FAILURE = "GET_COMPNIES_FAILURE";


export const POST_COMPNIES_REQUEST = "POST_COMPNIES_REQUEST";
export const POST_COMPNIES_SUCCESS = "POST_COMPNIES_SUCCESS";
export const POST_COMPNIES_FAILURE = "POST_COMPNIES_FAILURE";


export const GET_JOBSDATA_REQUEST = "GET_JOBSDATA_REQUEST";
export const GET_JOBSDATA_SUCCESS = "GET_JOBSDATA_SUCCESS";
export const GET_JOBSDATA_FAILURE = "GET_JOBSDATA_FAILURE";


export const GET_SINGLE_JOBDATA_REQUEST = "GET_SINGLE_JOBDATA_REQUEST";
export const GET_SINGLE_JOBDATA_SUCCESS = "GET_SINGLE_JOBDATA_SUCCESS";
export const GET_SINGLE_JOBDATA_FAILURE = "GET_SINGLE_JOBDATA_FAILURE";


